language: go
go:
- 1.12.x
install:
- go get github.com/sensu/sensu-check-log ./...
script:
- go test -v -race ./...

before_script:
- echo "REPO $TRAVIS_REPO_SLUG TAG ${TRAVIS_TAG}"

deploy:
  - #goreleaser
    provider: script
    script: curl -sL https://git.io/goreleaser | bash
    skip_cleanup: true
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux

after_deploy:
  - git clone https://github.com/sensu/sensu-go-bonsai-asset.git bonsai
  - bonsai/generate-sha512sum.sh
  - bonsai/github-release-upload.sh github_api_token=$GITHUB_TOKEN repo_slug="$TRAVIS_REPO_SLUG" tag="${TRAVIS_TAG}" filename="dist/$(cat dist/sha512_file)"

env:
  global:
  - secure: FIXME
  - GO111MODULE: 'on'
